// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAxVYo3TiIjffKn9Wlg4NneCzMtolAOhA',
    appId: '1:954322287988:web:14ef0501bd0357ea454021',
    messagingSenderId: '954322287988',
    projectId: 'counter-app-6b903',
    authDomain: 'counter-app-6b903.firebaseapp.com',
    storageBucket: 'counter-app-6b903.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUFzJtTU58RI-aXmpFKhs3tBzczUMYTHA',
    appId: '1:954322287988:android:79bee4fe30dfbcfb454021',
    messagingSenderId: '954322287988',
    projectId: 'counter-app-6b903',
    storageBucket: 'counter-app-6b903.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-3AfwQg8HtgyMxXieBU04ZkaHgr4djic',
    appId: '1:954322287988:ios:d95b8a43124fcaa0454021',
    messagingSenderId: '954322287988',
    projectId: 'counter-app-6b903',
    storageBucket: 'counter-app-6b903.appspot.com',
    iosClientId: '954322287988-b5db1jgj927br6a2390u1msc560gb72o.apps.googleusercontent.com',
    iosBundleId: 'com.kadatska.counterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-3AfwQg8HtgyMxXieBU04ZkaHgr4djic',
    appId: '1:954322287988:ios:cec13c3a20e4dbbc454021',
    messagingSenderId: '954322287988',
    projectId: 'counter-app-6b903',
    storageBucket: 'counter-app-6b903.appspot.com',
    iosClientId: '954322287988-q5rend7b5our7kgktgfsjib3rur5km0g.apps.googleusercontent.com',
    iosBundleId: 'com.kadatska.counterApp.RunnerTests',
  );
}
